spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=system
spring.datasource.password=manager

#We can move below common properties to application.properties file.
#spring.datasource.tomcat.initialSize=20
#spring.datasource.tomcat.max-active=25
#debug=true
